FROM python:3.8-buster

RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /celery_worker

COPY . .

RUN wget https://www.dropbox.com/s/04suaimdpru76h3/ArtLine_920.pkl?dl=1 
RUN mv ArtLine_920.pkl?dl=1 ArtLine_920.pkl

RUN pip install -r requirements.txt

ENTRYPOINT celery -A tasks worker --loglevel=INFO