version: "3.3"
services:
  celery_worker:
    build: ./celery_worker
    restart: always
    depends_on:
      - redis

  flask_app:
    build: ./flask_app
    depends_on:
      - redis
    ports:
      - "80:8080"

  redis:
    image: "redis"
    ports:
      - "6379:6379"